---
title: "Homework 3"
author: "JR Chansakul"
date: 2020-10-05
output: github_document
  
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
	fig.width = 6, 
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

```{r}
data("instacart")

view(instacart)
```

This dataset contains `r nrow(instacart)` rows and `r ncol(instacart)`columns. 

Observations are the level of items in orders by user. There are user / order variables -- user ID, order ID, order day, and order hour. There are also item variables -- name, aisle, department, and some numeric codes. 


How many aisles, and which are most items from?

```{r}
instacart %>% 
	count(aisle) %>% 
  arrange(desc(n))
```


Let's make a plot.

```{r}
instacart %>% 
	count(aisle) %>% 
	filter(n > 10000) %>% 
  mutate(
		aisle = factor(aisle),
		aisle = fct_reorder(aisle, n)
    ) %>% 
  	ggplot(aes(x = aisle, y = n)) + 
    geom_point() +
  	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

```

















## Problem 2

## Problem 3


